WizardFactory/BlogSyncer

routes/twitter.js

JUS-95 : Twitter 모아보기 및 나머지 기능 확인후 추가해야함

---

routes/google.js

JUS-91 Google Invalid Credentials 에러 수정하기. Fixed #125

JUS-91 Google Invalid Credentials 에러 수정하기. Fixed #125

---

.jshintrc
app.js
models/blogdb.js
models/groupdb.js
models/historydb.js
models/postdb.js
models/userdb.js
routes/blogRoutes.js
routes/blogbot.js
routes/facebook.js
routes/google.js
routes/kakao.js
routes/log.js
routes/tistory.js
routes/tumblr.js
routes/twitter.js
routes/wordpress.js

JUS-97 Log style를 정리하자. fixed #140
log용 meta추가 및 정리.
log.js 수정.

JUS-97 Log style를 정리하자. fixed #140

---

public/javascripts/controller.js
public/views/blog/collectFeedback.html

JUS-99 모아보기에서 blogid대신에 blog name이 나오게 수정. Fixed #145
* controller.js
init()에서 sites정보를 가지고 와서 scope에 저장
getBlogTitle 함수 추가.
* collectFeedback.html
getBlogTitle call하여 blogId대신에 blogTitle이 출력되게 수정.

JUS-99 모아보기에서 blogid대신에 blog name이 나오게 수정. Fixed #145

---

public/javascripts/controller.js

* controller.js
- sites를 scope에서 떼어내서 local variable로 변경함.
- sites정보를 init 가장 처음에 넣어서 getBlogTitle()시에 sites가 없는 경우 방지.

JUS-102 scope에 붙이지 말고 일반 변수로 정의해도 되지 않아요? Fixed #149

---

test/test_blogdb.js
test/test_groupdb.js
test/test_historydb.js
test/test_postdb.js
test/test_userdb.js

Fixed #154 JUS-106 test unit 에러 수정하기.
* test_XXXX.js
winston을 global.log에 추가하여 test에 require된 module에서 log를 사용할 때 에러 발생하는 문제 수정.

Fixed #154 JUS-106 test unit 에러 수정하기.

---

routes/blogbot.js
routes/facebook.js

'/bot_posts/:blog_id', 
'/bot_posts/:blog_id/:post_id' 구현 완료 
기본 feed(담벼락)은 확인 못해봄. 권한 문제인지 확인 필요.

#88 JUS-68 Facebook 페이지 및 글 가져오기

---

routes/facebook.js
routes/google.js
routes/kakao.js
routes/tistory.js
routes/tumblr.js
routes/twitter.js
routes/userManager.js
routes/wordpress.js

* 각 blog js에서 UserMgr을 통해 UserDb 접근하도록 변경
* provider name을 정의하여 사용하도록 수정

JUS-105 UserDb 관련 코드를 UserMgr로 정리

---

routes/tistory.js

Fixed #26 JUS-47 tistory의 경우 posts를 가지고 올때 category id만 존재함.
* tistory.js
_getCategoryIds(), _getCategoryNameById()를 추가함.
post list나 단일 post를 가지고 오기 전에 _getCategoryIds()를 통하여 category 정보를 먼저 가지고 온다.
send_post.category에 데이터를 넣기 전에 받은 categoryid를 _getCategoryNameById 함수 사용하여 name으로 변경한다.

Fixed #26 JUS-47 tistory의 경우 posts를 가지고 올때 category id만 존재함.

---

public/javascripts/controller.js
public/stylesheets/style.css
public/views/blog/registerBlog.html

JUS-115 블로그 등록에서 기존에 생성되어 있는 그룹의 경우 추가되지 않도록 처리
* 등록할 그룹에 하나의 블로그만 선택되어 있는 경우 추가하지 않고 메시지 표시
* 이미 등록된 그룹의 경우 추가하지 않고 메시지 표시
* 그룹 삭제 시 블로그 하나가 아닌 그룹 단위로 삭제되도록 변경
* 그룹 생성 시 선택할 블로그 목록을 초기 Show 상태로 변경
* 처음 블로그 선택 시 선택되지 않는 문제 수정

JUS-115 블로그 등록에서 기존에 생성되어 있는 그룹의 경우 추가되지 않도록 처리

---

public/javascripts/controller.js
public/javascripts/core.js
public/views/blog/registerBlog.html

Fixed JUS-99 모아보기에서 blogid대신에 blog name이 나오게 수정.
* controller.js
- blogCollectFeedbackCtrl에서 disselectAllBlog시에 아직 sites정보를 못가지고 온 경우 예외처리.
- http.get("/blogs/sites") 부분은 factory Site.pullSitesFromServer 로 이동.
* core.js
- factory('Site') 추가
* registerBlog.html
- blog id 대신 blog title 표시하도록 수정.

Fixed JUS-99 모아보기에서 blogid대신에 blog name이 나오게 수정.

---

models/groupdb.js
public/javascripts/controller.js
public/javascripts/core.js
public/stylesheets/style.css
public/views/blog/registerBlog.html
routes/blogRoutes.js
routes/blogbot.js

* GroupDB에 GroupInfo 추가
* Group 생성 시에 GroupInfo를 Default로 생성
* 수정된 GroupInfo를 GroupDB에 저장
* GroupDB에서 SyncInfo를 찾는 함수 추가
* 상세 설정 화면 추가
** Table 스타일로 Cell Click으로 Sync On/Off 변경
** Table 스타일의 Design 수정 또는 다른 스타일 고려 필요
** Blog Id 대신에 title로 표시

JUS-116 블로그 등록의 상세 설정 기능 추가

---

models/postdb.js
public/javascripts/controller.js
routes/blogbot.js
routes/kakao.js

#182 JUS-124 tumblr, kakao stroy, twitter, Facebook link post api 추가하기.
* postdb.js
** log 수정
* controller.js
** groupinfo가 없는 경우, post로 셋팅함.
* blogbot.js
** _cbSendPostToBlogs - postType체크
** _requestPostContent - postType 파라미터 추가
** _cbAddPostInfoToDb - oPostInfo  파라미터 추가
** findPostByPostIdOfBlog에 postId는 String으로 넘기도록 수정.
* kakao.js
** userMgr._getUserId 사용시에 res 정보 추가 전달.
** _postText, _postLink, _responsePostResult 새로 만듬.

#182 JUS-124 tumblr, kakao stroy, twitter, Facebook link post api 추가하기.

---

routes/twitter.js

* twitter.js
** router에서 에러 발생시에 response 안하는 버그 수정.
** jshint error 수정 (++ -> +=1, 이등연산자를 삼등연산자로)
** error발생시에 response에 status추가하도록 수정.

Fixed #174 JUS-118 모아보기에서 블로그 등록 화면으로 이동 시 그룹 및 블로그 정보가 보이지 않는 문제

---

routes/twitter.js

Fixed #175 JUS-119 모아보기(Twitter) retweet & like 못가져오는 버그
send_data변수를 필요한 내용에 따라 구분하였음.
add _convertBotPosts, _convertBotPost
post_id를 id 대신에 id_str를 사용한다. show/{id}.json에서 id가 id_str이어야 동작한다.

Fixed #175 JUS-119 모아보기(Twitter) retweet & like 못가져오는 버그

---

public/views/blog/collectFeedback.html
public/views/blog/historySync.html
public/views/blog/registerBlog.html
public/views/blog/setSync.html
public/views/home.html
public/views/signin.html

#216 google analytics 달기.

---

controllers/blogbot.js
controllers/userManager.js
models/userdb.js
routes/google.js
routes/kakao.js

google.js error 발생시에 response를 전달하지 않고, return 하지 않는 문제 수정.
Fixed #219 #125 kakao api token 만기 갱신하기 401 InvalidTokenException

google.js error 발생시에 response를 전달하지 않고, return 하지 않는 문제 수정.

---

controllers/blogbot.js
models/blogdb.js

Fixed #221 blogger post수가 20개 미만일때, _recursiveGetPosts가 멈추지 않는 문제.
update recursiveGetPosts.
etc
change log level in blogdb.js

Fixed #221 blogger post수가 20개 미만일때, _recursiveGetPosts가 멈추지 않는 문제.

---

controllers/blogbot.js
controllers/log.js
models/blogdb.js
models/groupdb.js
models/postdb.js
package.json
routes/tumblr.js

Fixed #225 log level이 제대로 동작하지 않는 문제.

---

routes/tistory.js

Fixed #242 tistory에서 게시글 가져오기와 글읽기 API에 tag가 없음.

---

controllers/blogbot.js
controllers/userManager.js
routes/facebook.js
routes/google.js
routes/kakao.js
routes/tistory.js
routes/tumblr.js
routes/twitter.js
routes/wordpress.js

Fixed #245 userManager.js의 함수 중에서 외부에서 접근함수는 함수이름에서 _제거

Fixed #245 userManager.js의 함수 중에서 외부에서 접근함수는 함수이름에서 _제거

---

controllers/blogConvert.js

Fixed #249 media post의 경우에 text post로 변경하여 저장하는 blogger, wordpress 등등에서 너무 큰 문제
* max-width:100% 로 지정하여 최대 parent의 width로 설정되도록 함

Fixed #249 media post의 경우에 text post로 변경하여 저장하는 blogger, wordpress 등등에서 너무 큰 문제

---

app.js
controllers/blogConvert.js
controllers/blogbot.js
models/blogdb.js
models/botFormat.js
models/groupdb.js
package.json
routes/blogRoutes.js
routes/facebook.js
routes/google.js
routes/kakao.js
routes/tistory.js
routes/tumblr.js
routes/twitter.js
routes/wordpress.js
test/test_blogConvert.js
test/test_data.js

rename blogbot.js to blogBot.js
mergetTagsCategories before BlogBot._requestPostContent
add mergeTagsCategories() to blogConvert.js
add categories array to blogdb and groupdb
update botBlogList to get cotegories
get categories info when getting botBlogList.

category tag 맞추어 동기화 하기. Fixed #214

---

controllers/blogConvert.js
routes/google.js
routes/tistory.js
test/test_blogConvert.js
test/test_data.js

add convertNewLineToBreakTag
convert newline to breaktag on google, tistory

Fixed #241 kakao story의 note post가 blogger에서 줄바꿈되지 않는 문제.

---

routes/facebook.js
routes/kakao.js
routes/twitter.js

Facebook에 새글이 들어갈때 html삭제 안되는 문제 수정.
remove html tag when posting on facebook
kakao story에 link posting할때, 사용자 설명이 link 설명으로 들어가는 문제 수정.
fixed set wrong postion of content when posting on kakao story.

Fixed #285, Fixed #284 error link posting on facebook,kakakostory

---

test/e2e/test_protractor.js

e2e에서 테스트용으로 포스팅한 글을 확이하는 테스트 항목 추가.

Fixed  #287 포스팅 된 글 확인

---

routes/facebook.js

Fixed #271 get urls of Facebook feed and pages.

---

controllers/blogbot.js
controllers/userManager.js
routes/google.js

convert tokenExpireTime from string to Date object.
add comment about makeTokenExpireTime(), updateAccessToken()

Fixed #250 google access token update 요청이 계속 되는 문제.

---

.gitignore
.jshintrc
app.js
bin/www
circle.yml
config/all.js
controllers/blogbot.js
models/blogdb.js
models/botFormat.js
models/groupdb.js
models/postdb.js
models/userdb.js
routes/facebook.js
routes/google.js
routes/kakao.js
routes/tistory.js
routes/tumblr.js
routes/twitter.js
routes/wordpress.js

new file
.gitignore
circle.yml : add deployment info
config file change from scvConfig.json to config/all.js
use strict moves to top of file.
.jshintrc
disable maxparams
enable maxlen to 120

make circle.yml Fixed #297

---

app.js
controllers/blogBot.js
controllers/blogConvert.js
models/groupdb.js
models/postdb.js
routes/facebook.js
routes/google.js
routes/kakao.js
routes/tistory.js
routes/tumblr.js
routes/twitter.js
routes/wordpress.js

twitter.js
support post type
tumblr.js
if botPost has teaser, it converts to text post when it posts new post
새로 등록할 object에 teaser가 있는 경우 text post작성.
blogConvert.js
Fixed line length
set urls to default in makeLimitString
urls 기본값 설정.
kakao.js
Fixed error add tags when get post
tags값 잘 못 넣는 문제 수정.
blogBot.js
updateAccessToken before getAndPush
change log level

Fixed #302 support post type of twitter

---

controllers/blogBot.js
models/blogdb.js
models/botFormat.js
routes/facebook.js
test/test_blogBot.js
test/test_blogConvert.js
test/test_botFormat.js
test/test_data.js

add getBlogInUser to blogBot
add accessToken to blogs of siteSchema
add _getBotBlog to facebook

Fixed #306 posting with access token of Facebook each page

---

app.js
controllers/log.js

set log level to info and make logfile on  development mode
set log level to debug on production mode without logfile.
app.js
set task interval time to 1 min

#309 log system

---

controllers/blogBot.js
controllers/log.js
routes/facebook.js
routes/kakao.js
routes/tistory.js
routes/twitter.js

change blogid of kakao from displayName to id
etc
Skip _cbAddPostsFromNewBlog at _cbAddBlogsToDb
remove encodeURIComponent for blogId when _requestPostContent
blog id is only ascii
check updated_time of post when get posts from facebook

kakao posts 요청시에 bad request발생하는 문제. Fixed #320

---

models/postdb.js
routes/kakao.js

get link_info via blogBot.getTeaser when fail to get by kakao api
TODO: upload image
update log message in getInfoFromPostInfo.

Fixed #305 kakao story link post 생성시에 error code -604 에 대한 보안책 필요.

---

app.js
controllers/blogBot.js
controllers/userManager.js
public/javascripts/controller.js
public/javascripts/core.js
public/views/signin.html
public/views/strings/en.json
public/views/strings/ko.json

* 로그인 화면에서 로그인 된 계정 중에 제거하는 기능 추가
* Provider가 하나만 있는 경우에는 삭제되지 않도록 함(차후에 탈퇴 기능이 필요함)

Fixed #272 특정 계정(account) 제거하기

---

app.js
controllers/blogBot.js

change setInterval to setTimeout for starting task on app.js
use async module for sequencial function call in blogBot.js
async모듈을 사용하여 함수들은 순차적으로 동작하게 만듬.
lower loglevel to prevent multi notification at error event
error발생에 중복 알림을 해결하기 위해 blogbot의 loglevel을 warn으로 수정함.

Fixed #326 blogbot task 개선하기.

---

routes/kakao.js

_pushPostsFromKakao 에서 rawPost.content가 비어 있는 경우에 space 추가.

Fixed #331 share at story on kakao stroy

---

app.js

310_create_robots.txt

---

controllers/blogBot.js
test/test_blogBot.js

twitter에서 작성한 글이 kakao story에 두번 올라가는 문제. Fixed #335

---

.travis.yml
circle.yml
package.json
test/test_blogBot.js

add .travis.yml
remove cricle.yml

#346 setup travis with openshfit

---

package.json

임시책으로 npm 원본에 적용되지 않았으나, 수정된  https://github.com/kimalec/passport-tistory 를 사용

#354 opensift에서 tistory login시에 죽는 문제.

---

.travis.yml

.travis.yml에 openshift 계정정보 삭제
travis에 환경변수 추가 및 .travis.yml에 환경변수 값 대입
테스트 프로젝트를 생성해서 테스트 했습니다.

Fixed #356 openshift 계정 정보 삭제
